version: '3.8'
services:
  mysql8:
    build:
      context: ./mysql
    container_name: "${COMPOSE_PROJECT_NAME}-mysql8"
    ports:
      - '3306:3306'
    env_file:
      - ./env/db.env
    volumes:
      - ./db/mysql:/var/lib/mysql

  api:
    build:
      context: .
    container_name: "${COMPOSE_PROJECT_NAME}-api"
    command: ./run_server.sh
    ports:
      - '3000:3000'
    env_file:
      - ./env/api.env
    volumes:
      - .:/project_name:cached
      - bundle:/usr/local/bundle
      - rails_cache:/project_name/tmp/cache
    depends_on:
      - db

volumes:
  mysql8:
    driver: local
  bundle:
    driver: local
  rails_cache:
    driver: local
