version: '3.8'
services:
  mysql8:
    build:
      context: ./mysql
    container_name: "${COMPOSE_PROJECT_NAME}-mysql8"
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/mysql:/var/lib/mysql

  api:
    build:
      context: .
    container_name: "${COMPOSE_PROJECT_NAME}-api"
    command: ./run_server.sh
    ports:
      - '3000:3000'
    environment:
      - MYSQL_HOST=mysql8
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    volumes:
      - .:/project_name:cached
      - bundle:/usr/local/bundle
      - node_modules:/project_name/node_modules
      - packs:/project_name/public/packs
      - rails_cache:/project_name/tmp/cache
    depends_on:
      - db

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  packs:
    driver: local
  rails_cache:
    driver: local
