version: '3.8'
services:
  db:
    build:
      context: ./mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - default
  api:
    build:
      context: .
    command: ./run_server.sh
    ports:
      - '3000:3000'
    environment:
      - MYSQL_HOST=db
    volumes:
      - .:/project_name:cached
      - bundle:/usr/local/bundle
      - node_modules:/project_name/node_modules
      - packs:/project_name/public/packs
      - rails_cache:/project_name/tmp/cache
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - default
    tmpfs:
      - /tmp
volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  packs:
    driver: local
  rails_cache:
    driver: local
